[theme]
# Primary accent color for interactive elements.
primaryColor = "#7abd7c"

# Background color for the main content area.
backgroundColor =  "#006400"

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor = "#dbe8db"

# Color used for almost all text.
textColor = "#0e0e0e"

# Font family for all text in the app, except code blocks. One of "sans serif", "sans" or
# Default: "sans"
font = "sans serif"




